### ISSUE TITLE
Doesn't work on OS X or Linux

### ISSUE THREAD

**Issue by thebyrd** [jamesryanbell/node-wraith#2]
```
$ wraith
env: node\r: No such file or directory
```

similar to https://github.com/busterjs/buster/issues/401

**Comment by jamesryanbell** [comment]
Hi

I have done some major changes to the script and part of these changes was adding os x compatibility. I need to update the readme tomorrow but just wanted to let you know the changes have been done.

Sorry this has taken so long for me to look at!

Thanks,
James

**Comment by JakobP** [comment]
@jamesryanbell
I got it working on Ubunto 14.04.

All that is needed is to make a symlink `ln -s /usr/bin/nodejs /usr/bin/node`.

It can also be done by installing the nodejs-legacy package, which is just a symlink.

Explanation: http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04
