### ISSUE TITLE
Controlling fuzz for difference testing

### ISSUE THREAD

**Issue by camsjams** [jamesryanbell/node-wraith#5]
Hi there - thanks for the great tool - I am user of the original version of the Wraith (https://github.com/BBC-News/wraith) running on Ruby and was giving your version a go.

Can you tell me how I can control the fuzz factor similar to the config in the original Wraith tool?

Their sample:
http://bbc-news.github.io/wraith/standard.html

**Comment by jamesryanbell** [comment]
Hi

Thanks for using the tool I hope it's working well for you :)

Unfortunately I haven't found a way to replicate the fuzz factor the ruby version has as I am not using imagemagick to do the image comparison. It is on my list of things to try and implement though so as soon as I find a way I will update the repo.

Thanks,
James

**Comment by camsjams** [comment]
Alright - good to know. Either way, great work and thanks again.
